
name: Build Android

on:
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Build
        run: |
          ln -s vulkan_android.pc vulkan.pc
          sudo apt update
          sudo apt install -y meson libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libx11-dev
          cp -R /usr/include/X11 include/
          cp -R /usr/include/xcb include/
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-drm-${{matrix.arch}} >build-crossfile-drm
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile-drm" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled \
            -Dfreedreno-kgsl=false
          ninja -C "build-android" install
          cd ..
          envsubst <android-${{matrix.arch}} >build-crossfile
          # -Dglx=gallium-xlib \
          meson "build-android" \
            --prefix=/tmp/virgl \
            --cross-file "build-crossfile" \
            --buildtype release \
            -Dplatforms=android \
            -Dplatform-sdk-version=24 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dshared-llvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=enabled \
            -Dgbm=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=virgl \
            -Dc_link_args='-flto=thin -Wl,-plugin-opt=-emulated-tls=0 -fuse-ld=lld' \
            -Dshared-glapi=false
          ninja -C "build-android" install
          # cp "build-android/src/gallium/drivers/zink/libzink.a" /tmp/virgl/lib/
          rm /tmp/virgl/lib/libOSMesa.so /tmp/virgl/lib/libOSMesa.so.8
          mv /tmp/virgl/lib/libOSMesa.so.8.0.0 /tmp/virgl/lib/libOSMesa.so.8
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip /tmp/virgl/lib/libOSMesa.so.8
      - name: Upload libraries
        uses: actions/upload-artifact@main
        with:
          name: libmesa_${{matrix.arch}}
          path: /tmp/virgl
